#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd)]
pub enum CommandStatus {
    Supported,
    Limited,
    PlanOnly,
    DiscoveryOnly,
    Deferred,
    RemovedFromScope,
}

impl CommandStatus {
    pub const fn is_agent_action_surface(self) -> bool {
        matches!(self, Self::Supported | Self::Limited | Self::PlanOnly)
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd)]
pub enum OfficeFormat {
    Pptx,
    Docx,
    Xlsx,
    Pdf,
    Json,
    Svg,
    Html,
    Png,
    Jpeg,
    Markdown,
    Text,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CommandSpec {
    pub command: &'static str,
    pub status: CommandStatus,
    pub human_visible: bool,
    pub agent_visible: bool,
    pub mutates_files: bool,
    pub supports_dry_run: bool,
    pub supported_formats: &'static [OfficeFormat],
    pub summary: &'static str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CompactCommandSpec {
    pub command: &'static str,
    pub status: CommandStatus,
    pub mutates_files: bool,
    pub supports_dry_run: bool,
    pub supported_formats: &'static [OfficeFormat],
    pub summary: &'static str,
}

const OFFICE_FORMATS: &[OfficeFormat] = &[
    OfficeFormat::Pptx,
    OfficeFormat::Docx,
    OfficeFormat::Xlsx,
    OfficeFormat::Pdf,
];
const OOXML_FORMATS: &[OfficeFormat] =
    &[OfficeFormat::Pptx, OfficeFormat::Docx, OfficeFormat::Xlsx];
const PREVIEW_FORMATS: &[OfficeFormat] = &[
    OfficeFormat::Pptx,
    OfficeFormat::Docx,
    OfficeFormat::Xlsx,
    OfficeFormat::Pdf,
    OfficeFormat::Svg,
    OfficeFormat::Html,
];
const REPORT_FORMATS: &[OfficeFormat] = &[
    OfficeFormat::Json,
    OfficeFormat::Markdown,
    OfficeFormat::Text,
];
const JSON_FORMATS: &[OfficeFormat] = &[OfficeFormat::Json];
const ASSET_FORMATS: &[OfficeFormat] = &[
    OfficeFormat::Pptx,
    OfficeFormat::Docx,
    OfficeFormat::Xlsx,
    OfficeFormat::Png,
    OfficeFormat::Jpeg,
    OfficeFormat::Svg,
];
const DIAGRAM_FORMATS: &[OfficeFormat] = &[OfficeFormat::Json, OfficeFormat::Svg];
const NO_FORMATS: &[OfficeFormat] = &[];

pub const COMMAND_REGISTRY: &[CommandSpec] = &[
    spec(
        "capabilities",
        CommandStatus::Supported,
        true,
        true,
        false,
        false,
        JSON_FORMATS,
        "Report the active v5 command surface and runtime capability contract.",
    ),
    spec(
        "help",
        CommandStatus::Supported,
        true,
        true,
        false,
        false,
        REPORT_FORMATS,
        "Show human and agent workflow help.",
    ),
    spec(
        "help workflow",
        CommandStatus::Supported,
        true,
        false,
        false,
        false,
        REPORT_FORMATS,
        "Show workflow-specific help and next commands.",
    ),
    spec(
        "help error",
        CommandStatus::Supported,
        true,
        false,
        false,
        false,
        REPORT_FORMATS,
        "Explain structured error classes and recovery commands.",
    ),
    spec(
        "config show",
        CommandStatus::Supported,
        true,
        false,
        false,
        false,
        JSON_FORMATS,
        "Inspect effective user and project configuration.",
    ),
    spec(
        "config set",
        CommandStatus::Limited,
        true,
        false,
        true,
        false,
        JSON_FORMATS,
        "Persist allowlisted configuration leaves with atomic project/user writes.",
    ),
    spec(
        "doctor",
        CommandStatus::Supported,
        true,
        true,
        false,
        false,
        JSON_FORMATS,
        "Check local runtime readiness and policy gaps.",
    ),
    spec(
        "inspect",
        CommandStatus::Supported,
        true,
        true,
        false,
        false,
        OFFICE_FORMATS,
        "Inspect Office/PDF structure and trusted metadata.",
    ),
    spec(
        "view",
        CommandStatus::Limited,
        true,
        true,
        true,
        false,
        PREVIEW_FORMATS,
        "Create previews and object-map artifacts for supported documents.",
    ),
    spec(
        "edit",
        CommandStatus::Limited,
        true,
        true,
        true,
        true,
        OOXML_FORMATS,
        "Apply scoped EditOps with selector resolution and dry-run support.",
    ),
    spec(
        "render",
        CommandStatus::Limited,
        true,
        true,
        true,
        false,
        OFFICE_FORMATS,
        "Render validated IR into Office/PDF artifacts.",
    ),
    spec(
        "scaffold",
        CommandStatus::Supported,
        true,
        false,
        true,
        false,
        JSON_FORMATS,
        "Create starter IR without model inference.",
    ),
    spec(
        "export",
        CommandStatus::Limited,
        true,
        false,
        true,
        false,
        OFFICE_FORMATS,
        "Export supported formats with explicit fidelity caveats.",
    ),
    spec(
        "validate",
        CommandStatus::Supported,
        true,
        true,
        false,
        false,
        JSON_FORMATS,
        "Validate schemas, structure, and quality gates.",
    ),
    spec(
        "verify",
        CommandStatus::Limited,
        true,
        true,
        false,
        false,
        OFFICE_FORMATS,
        "Verify openability, readiness, and optional visual/native proof.",
    ),
    spec(
        "diagnose",
        CommandStatus::Limited,
        true,
        false,
        false,
        false,
        OFFICE_FORMATS,
        "Detect document risks and repair candidates.",
    ),
    spec(
        "repair",
        CommandStatus::Limited,
        true,
        false,
        true,
        true,
        OFFICE_FORMATS,
        "Repair supported issues or produce a dry-run repair plan.",
    ),
    spec(
        "diff",
        CommandStatus::Limited,
        true,
        true,
        false,
        false,
        OFFICE_FORMATS,
        "Compare Office/PDF files semantically and visually where available.",
    ),
    spec(
        "prepare",
        CommandStatus::Limited,
        true,
        false,
        true,
        false,
        OFFICE_FORMATS,
        "Prepare AI-readable reference and target artifacts.",
    ),
    spec(
        "prepare reference",
        CommandStatus::Limited,
        true,
        false,
        true,
        false,
        OFFICE_FORMATS,
        "Prepare a reference artifact for downstream workflows.",
    ),
    spec(
        "manifest",
        CommandStatus::Limited,
        true,
        false,
        true,
        false,
        JSON_FORMATS,
        "Create artifact manifests for runs and handoff.",
    ),
    spec(
        "manifest inspect",
        CommandStatus::Supported,
        true,
        false,
        false,
        false,
        JSON_FORMATS,
        "Inspect a run or artifact manifest.",
    ),
    spec(
        "manifest verify",
        CommandStatus::Deferred,
        false,
        false,
        false,
        false,
        JSON_FORMATS,
        "Deferred manifest verification surface.",
    ),
    spec(
        "select",
        CommandStatus::Supported,
        true,
        false,
        false,
        false,
        OFFICE_FORMATS,
        "Resolve safe document selectors with confidence metadata.",
    ),
    spec(
        "plan",
        CommandStatus::PlanOnly,
        true,
        false,
        false,
        false,
        JSON_FORMATS,
        "Turn a goal into deterministic candidate EditOps without writing documents.",
    ),
    spec(
        "rollback",
        CommandStatus::Limited,
        true,
        false,
        true,
        false,
        OFFICE_FORMATS,
        "Restore artifacts from explicit transaction records.",
    ),
    spec(
        "lock",
        CommandStatus::Limited,
        true,
        false,
        true,
        false,
        JSON_FORMATS,
        "Create and inspect scoped multi-agent edit locks.",
    ),
    spec(
        "merge",
        CommandStatus::Deferred,
        false,
        false,
        true,
        false,
        OOXML_FORMATS,
        "Deferred artifact merge surface.",
    ),
    spec(
        "run",
        CommandStatus::Supported,
        true,
        true,
        true,
        false,
        JSON_FORMATS,
        "Run a local JSON workflow with strict output-root, manifest, trace, and summary artifacts.",
    ),
    spec(
        "run prepare-reference",
        CommandStatus::Deferred,
        false,
        false,
        true,
        false,
        OFFICE_FORMATS,
        "Deferred prepare-reference workflow alias.",
    ),
    spec(
        "run office-edit",
        CommandStatus::Deferred,
        false,
        false,
        true,
        true,
        OOXML_FORMATS,
        "Deferred office-edit workflow alias.",
    ),
    spec(
        "run office-agent",
        CommandStatus::Deferred,
        false,
        false,
        true,
        false,
        OFFICE_FORMATS,
        "Deferred office-agent workflow alias.",
    ),
    spec(
        "critique",
        CommandStatus::PlanOnly,
        true,
        false,
        false,
        false,
        OFFICE_FORMATS,
        "Return quality critiques and risks without mutating documents.",
    ),
    spec(
        "improve",
        CommandStatus::PlanOnly,
        true,
        false,
        false,
        true,
        OFFICE_FORMATS,
        "Produce improvement suggestions and optional plans without document writes.",
    ),
    spec(
        "benchmark run",
        CommandStatus::DiscoveryOnly,
        true,
        false,
        true,
        false,
        JSON_FORMATS,
        "Run optional benchmark corpus checks for release evidence.",
    ),
    spec(
        "benchmark compare",
        CommandStatus::DiscoveryOnly,
        true,
        false,
        false,
        false,
        JSON_FORMATS,
        "Compare benchmark reports.",
    ),
    spec(
        "asset inspect",
        CommandStatus::Limited,
        true,
        true,
        false,
        false,
        ASSET_FORMATS,
        "Inspect embedded and standalone media assets.",
    ),
    spec(
        "asset extract",
        CommandStatus::Limited,
        true,
        true,
        true,
        false,
        ASSET_FORMATS,
        "Extract embedded media from supported Office packages.",
    ),
    spec(
        "asset replace",
        CommandStatus::Limited,
        true,
        true,
        true,
        false,
        ASSET_FORMATS,
        "Replace existing embedded media with guarded package writes.",
    ),
    spec(
        "chart render",
        CommandStatus::Limited,
        true,
        true,
        true,
        false,
        DIAGRAM_FORMATS,
        "Render supported chart specs into SVG assets.",
    ),
    spec(
        "diagram render",
        CommandStatus::Limited,
        true,
        true,
        true,
        false,
        DIAGRAM_FORMATS,
        "Render safe diagram text into SVG assets.",
    ),
    spec(
        "schema list",
        CommandStatus::Supported,
        true,
        true,
        false,
        false,
        JSON_FORMATS,
        "List bundled schemas.",
    ),
    spec(
        "schema get",
        CommandStatus::Supported,
        true,
        true,
        false,
        false,
        JSON_FORMATS,
        "Return a bundled schema by id.",
    ),
    spec(
        "schema fetch",
        CommandStatus::Supported,
        true,
        true,
        false,
        false,
        JSON_FORMATS,
        "Alias for schema get.",
    ),
    spec(
        "schema validate",
        CommandStatus::Supported,
        true,
        true,
        false,
        false,
        JSON_FORMATS,
        "Validate JSON input against a bundled schema.",
    ),
    spec(
        "schema migrate",
        CommandStatus::PlanOnly,
        true,
        false,
        true,
        false,
        JSON_FORMATS,
        "Plan or write schema migrations where available.",
    ),
    spec(
        "errors list",
        CommandStatus::Supported,
        true,
        true,
        false,
        false,
        JSON_FORMATS,
        "List machine-readable error codes.",
    ),
    spec(
        "errors inspect",
        CommandStatus::Supported,
        true,
        true,
        false,
        false,
        JSON_FORMATS,
        "Inspect a machine-readable error code.",
    ),
    spec(
        "template list",
        CommandStatus::DiscoveryOnly,
        true,
        false,
        false,
        false,
        JSON_FORMATS,
        "List local template metadata.",
    ),
    spec(
        "template inspect",
        CommandStatus::Supported,
        true,
        true,
        false,
        false,
        JSON_FORMATS,
        "Inspect a local template definition.",
    ),
    spec(
        "template candidates",
        CommandStatus::PlanOnly,
        true,
        false,
        false,
        false,
        OFFICE_FORMATS,
        "Generate template candidates from a source document.",
    ),
    spec(
        "template create",
        CommandStatus::Deferred,
        false,
        false,
        true,
        false,
        JSON_FORMATS,
        "Deferred template authoring surface.",
    ),
    spec(
        "template apply-map",
        CommandStatus::PlanOnly,
        true,
        false,
        true,
        false,
        JSON_FORMATS,
        "Create an apply-map plan for a template.",
    ),
    spec(
        "template validate",
        CommandStatus::Supported,
        true,
        false,
        false,
        false,
        JSON_FORMATS,
        "Validate template metadata and mappings.",
    ),
    spec(
        "template fill",
        CommandStatus::Limited,
        true,
        true,
        true,
        false,
        OOXML_FORMATS,
        "Fill safe OOXML text placeholders from JSON data while preserving package structure.",
    ),
    spec(
        "design list",
        CommandStatus::DiscoveryOnly,
        true,
        false,
        false,
        false,
        JSON_FORMATS,
        "List local design metadata.",
    ),
    spec(
        "design inspect",
        CommandStatus::DiscoveryOnly,
        true,
        false,
        false,
        false,
        JSON_FORMATS,
        "Inspect a local design definition.",
    ),
    spec(
        "design init",
        CommandStatus::PlanOnly,
        true,
        false,
        true,
        false,
        JSON_FORMATS,
        "Initialize design metadata.",
    ),
    spec(
        "design edit",
        CommandStatus::Deferred,
        false,
        false,
        true,
        false,
        JSON_FORMATS,
        "Deferred design editing surface.",
    ),
    spec(
        "design update",
        CommandStatus::Deferred,
        false,
        false,
        true,
        false,
        JSON_FORMATS,
        "Deferred design update surface.",
    ),
    spec(
        "design validate",
        CommandStatus::Supported,
        true,
        false,
        false,
        false,
        JSON_FORMATS,
        "Validate design metadata.",
    ),
    spec(
        "design capture",
        CommandStatus::Deferred,
        false,
        false,
        true,
        false,
        OFFICE_FORMATS,
        "Capture reusable design knowledge from a source document.",
    ),
    spec(
        "design apply",
        CommandStatus::Deferred,
        false,
        false,
        true,
        false,
        OOXML_FORMATS,
        "Deferred design apply surface.",
    ),
    spec(
        "layout apply",
        CommandStatus::Deferred,
        false,
        false,
        true,
        false,
        OOXML_FORMATS,
        "Deferred layout apply surface.",
    ),
    spec(
        "agent install",
        CommandStatus::Deferred,
        false,
        false,
        true,
        false,
        NO_FORMATS,
        "Deferred agent adapter installation surface.",
    ),
    spec(
        "agent refresh",
        CommandStatus::Deferred,
        false,
        false,
        true,
        false,
        NO_FORMATS,
        "Deferred agent adapter refresh surface.",
    ),
    spec(
        "mcp serve",
        CommandStatus::RemovedFromScope,
        false,
        false,
        false,
        false,
        NO_FORMATS,
        "MCP is removed from the native command scope.",
    ),
    spec(
        "renderer list",
        CommandStatus::DiscoveryOnly,
        true,
        false,
        false,
        false,
        JSON_FORMATS,
        "Discover renderer registrations without enabling native proof.",
    ),
    spec(
        "renderer inspect",
        CommandStatus::DiscoveryOnly,
        true,
        false,
        false,
        false,
        JSON_FORMATS,
        "Inspect renderer metadata.",
    ),
    spec(
        "renderer trust",
        CommandStatus::Deferred,
        false,
        false,
        true,
        false,
        NO_FORMATS,
        "Deferred renderer trust mutation surface.",
    ),
    spec(
        "renderer doctor",
        CommandStatus::DiscoveryOnly,
        true,
        false,
        false,
        false,
        JSON_FORMATS,
        "Diagnose external renderer availability and policy gaps.",
    ),
    spec(
        "plugin list",
        CommandStatus::RemovedFromScope,
        false,
        false,
        false,
        false,
        NO_FORMATS,
        "Plugins are outside the native command scope.",
    ),
    spec(
        "plugin inspect",
        CommandStatus::RemovedFromScope,
        false,
        false,
        false,
        false,
        NO_FORMATS,
        "Plugins are outside the native command scope.",
    ),
    spec(
        "plugin install",
        CommandStatus::RemovedFromScope,
        false,
        false,
        false,
        false,
        NO_FORMATS,
        "Plugins are outside the native command scope.",
    ),
    spec(
        "plugin trust",
        CommandStatus::RemovedFromScope,
        false,
        false,
        false,
        false,
        NO_FORMATS,
        "Plugins are outside the native command scope.",
    ),
];

pub fn command_registry() -> &'static [CommandSpec] {
    COMMAND_REGISTRY
}

pub fn find_command(command: &str) -> Option<&'static CommandSpec> {
    COMMAND_REGISTRY
        .iter()
        .find(|entry| entry.command == command)
}

pub fn human_visible_commands() -> Vec<&'static CommandSpec> {
    COMMAND_REGISTRY
        .iter()
        .filter(|entry| entry.human_visible)
        .collect()
}

pub fn agent_visible_commands() -> Vec<&'static CommandSpec> {
    COMMAND_REGISTRY
        .iter()
        .filter(|entry| entry.agent_visible && entry.status.is_agent_action_surface())
        .collect()
}

pub fn compact_agent_visible_commands() -> Vec<CompactCommandSpec> {
    agent_visible_commands()
        .into_iter()
        .map(|entry| CompactCommandSpec {
            command: entry.command,
            status: entry.status,
            mutates_files: entry.mutates_files,
            supports_dry_run: entry.supports_dry_run,
            supported_formats: entry.supported_formats,
            summary: entry.summary,
        })
        .collect()
}

const fn spec(
    command: &'static str,
    status: CommandStatus,
    human_visible: bool,
    agent_visible: bool,
    mutates_files: bool,
    supports_dry_run: bool,
    supported_formats: &'static [OfficeFormat],
    summary: &'static str,
) -> CommandSpec {
    CommandSpec {
        command,
        status,
        human_visible,
        agent_visible,
        mutates_files,
        supports_dry_run,
        supported_formats,
        summary,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mcp_is_removed_from_scope_and_hidden() {
        let mcp = find_command("mcp serve").expect("mcp serve is registered");

        assert_eq!(mcp.status, CommandStatus::RemovedFromScope);
        assert!(!mcp.agent_visible);
        assert!(!mcp.human_visible);
    }

    #[test]
    fn compact_agent_surface_contains_only_action_statuses() {
        let compact = compact_agent_visible_commands();

        assert!(!compact.is_empty());
        assert!(compact.iter().all(|entry| matches!(
            entry.status,
            CommandStatus::Supported | CommandStatus::Limited | CommandStatus::PlanOnly
        )));
    }
}
